server:
  port: 8888

logging:
  config: classpath:logback-spring.xml

cors:
  allow: true

kafka:
  topic:
    process-document: process_document
    response-document: response_document

outbox:
  scheduler:
    enable: true
    initialDelayMillis: 10000
    fixedDelayMillis: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        hbm2ddl:
          auto: none

  liquibase:
    change-log: classpath:db/changelog/master-changelog.xml

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: document_state_updaters